### ISSUE TITLE
Source class generation does not exist

### ISSUE THREAD

**Issue by rafaelstz** [davidalger/capistrano-magento2#101]
This message below showed up when I tried to deploy an upgrade from Magento Commerce 2.2.2 to 2.2.3.

```
INFO [f65ab318] Finished in 0.974 seconds with exit status 0 (successful).

 DEBUG [36d9b447] Running if test ! -d /home/myserver_staging/releases/20180409220900; then echo "Directory does not exist '/home/myserver_staging/releases/20180409220900'" 1>&2; false; fi as myserver_staging@myserver.magemojo.com

 DEBUG [36d9b447] Command: if test ! -d /home/myserver_staging/releases/20180409220900; then echo "Directory does not exist '/home/myserver_staging/releases/20180409220900'" 1>&2; false; fi

 DEBUG [36d9b447] Finished in 0.595 seconds with exit status 0 (successful).

 DEBUG [52413a6c] Running /usr/bin/env php -f /home/myserver_staging/releases/20180409220900/bin/magento -- -V --no-ansi as myserver_staging@myserver.magemojo.com

 DEBUG [52413a6c] Command: cd /home/myserver_staging/releases/20180409220900 && ( export PATH="/opt/remi/php70/root/usr/bin:$PATH" ; /usr/bin/env php -f /home/myserver_staging/releases/20180409220900/bin/magento -- -V --no-ansi )

 DEBUG [52413a6c] 	Source class "\Magento\Elasticsearch\Elasticsearch5\Model\Adapter\BatchDataMapper\CategoryFieldsProvider" for "Magento\Elasticsearch\Elasticsearch5\Model\Adapter\BatchDataMapper\CategoryFieldsProviderProxy" generation does not exist.

 DEBUG [52413a6c] 
```

It's the native module so when I update directly on the server I have no problems, I tried to use all `bin/magento` commands which I could imagine simulating that issue above but nothing caused it, I'm thinking that it issue could be caused by some Capistrano independent routine.

How could I solve it?

**Comment by davidalger** [comment]
@rafaelstz Sorry about the delayed reply here, but I'm afraid I have no solution for you. That error is clearly one coming from the Magento application code and not from this gem (and I don't know what is causing it). If you haven't already, you might ask on the Magento 2 forums of report the issue over on the Magento 2 Github to see what some of the maintainers have to offer up.
