### ISSUE TITLE
how to set allow_url_fopen=on for composer when it can't be enabled globally on production server

### ISSUE THREAD

**Issue by RaFr** [davidalger/capistrano-magento2#107]
allow_url_fopen must be enabled on the deployment server otherwise composer fails to download files. what is the best way to add "-d allow_url_fopen=On" to composer commands when allow_url_fopen can't be enabled globally ( no access to php.ini file) ?

**Comment by davidalger** [comment]
@RaFr I don't think there is an easy way to do this. That PHP setting needs to be enabled for Magento 2 to work properly, and there are things which simply will not work in the Magento admin with that setting turned off in Magento 2. If your hosting provider cannot enable that for you, I'd suggest maybe this is a reason to look somewhere else for hosting this Magento 2 site. As this is not an issue with the gem, I'm closing this out. Cheers!
