### ISSUE TITLE
How to clear memcache, redis etc?

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/capistrano-magento2#108]
We are using external cache system like memcache and redis.
Can you please mention the hook to be used for this purpose?

Thanks

**Comment by davidalger** [comment]
@MagePsycho I'm sorry for the delay here, and also I'm not sure what you're asking…so perhaps you might clarify? The tool by default calls `bin/magento cache:flush` immediately following publication of a new release. This is native behavior. For it to flush Redis or memcache, well Magento does that when redis or memcache is configured as the cache backend in Magento.
