### ISSUE TITLE
Log whether deployment upgrades schema/data to revisions.log

### ISSUE THREAD

**Issue by erikhansen** [davidalger/capistrano-magento2#111]
As you know, Capistrano writes a deployment log to a revisions.log file

```
Branch master (at 71b66dcb839a96c08a4267ad6a22d50fb8b65d62) deployed as release 20180828204741 by erikhansen
Branch master (at 667e4b22d6e4b034fb6a55484de922f49c01b6e3) deployed as release 20180910172458 by erikhansen
Branch master (at 49b2ff1491fd3a30ee744d4464ff5163a282a71d) deployed as release 20180910181345 by billybob
Branch master (at d28ec68349dae31803cf6114acaab4ab63f590e2) deployed as release 20180913024203 by johnsmith
Branch master (at 05ee7ff938880650c6c0188a6caabec870335aaf) deployed as release 20180917032808 by veronicacostello
```

It would be nice if there was a string appended to the end of each line, with information about whether database schema/data changes were made during that deployment. In case a deployment needs to be rolled back, this would make it easy to know at a glance whether the deployment was a code-only deployment, or whether changes were made to the DB. Something like this (scroll to the right to see my suggested addition):

```
Branch master (at d28ec68349dae31803cf6114acaab4ab63f590e2) deployed as release 20180913024203 by johnsmith - Schema/data changes were made
Branch master (at 05ee7ff938880650c6c0188a6caabec870335aaf) deployed as release 20180917032808 by veronicacostello - No schema/data changes were made
```

Alternatively, this Gem could also log the specific DB changes, like this:

```
Branch master (at d28ec68349dae31803cf6114acaab4ab63f590e2) deployed as release 20180913024203 by johnsmith
    The following schema/data changes were made:
         Magento_Directory     schema:       2.0.1  ->  2.0.2      
         Magento_Directory       data:       2.0.1  ->  2.0.2      
          Magento_Customer     schema:      2.0.12  ->  2.0.13     
          Magento_Customer       data:      2.0.12  ->  2.0.13     
           Magento_Catalog     schema:       2.2.3  ->  2.2.4      
           Magento_Catalog       data:       2.2.3  ->  2.2.4      
             Magento_Quote     schema:       2.0.6  ->  2.0.7      
             Magento_Quote       data:       2.0.6  ->  2.0.7      
             Magento_Sales     schema:       2.0.7  ->  2.0.9      
             Magento_Sales       data:       2.0.7  ->  2.0.9      
        Magento_Newsletter     schema:       2.0.0  ->  2.0.1      
        Magento_Newsletter       data:       2.0.0  ->  2.0.1      
             Magento_Vault     schema:       2.0.2  ->  2.0.3      
             Magento_Vault       data:       2.0.2  ->  2.0.3  
Branch master (at 05ee7ff938880650c6c0188a6caabec870335aaf) deployed as release 20180917032808 by veronicacostello
    No schema/data changes were made
```

Let me know if you think this would be valuable. If so, I might try to make time to add this.

**Comment by davidalger** [comment]
I can certainly see the usefulness of this. The logging is a core part of the Capistrano, so implementing it will likely require straight up re-implementation of the `deploy:log_revision` task.

A simpler alternative approach may be to add a `capistrano-magento2.log` file and log the revision and timestamp as is done in `revisions.log` but include the extra information on whether maintenance mode was used, the schema/data changes made (i.e. output from the setup:db:status command). It'd be super cool if the duration of the deployment and/or downtime window could be included in that.

**Comment by erikhansen** [comment]
I like your simpler approach, including the extra info you suggested. If/when I have time, I'll implement this. I'll ping you before starting to implement it, in case you get inspired and decide to work on it.

**Comment by davidalger** [comment]
Closing this for now due to inactivity; don't have availability to do anything with it myself.

**Comment by erikhansen** [comment]
No problem. I've not yet run into a situation where I've needed this. And if I did, it wouldn't take too much time to parse through the `var/capistrano.log` files (from the computer(s) that did the deployments) to determine if previous deployments resulted in schema upgrades. Probably for the best that neither of us made time to implement this.
