### ISSUE TITLE
Adding a new theme gives an issue with production mode

### ISSUE THREAD

**Issue by PascalBrouwers** [davidalger/capistrano-magento2#113]
`magento:setup:static-content:deploy` gives an issue because the new theme is not installed yet. Running `bin/magento setup:upgrade` before running static-content fixes it.

**Comment by hostep** [comment]
I believe this is a duplicate of: https://github.com/davidalger/capistrano-magento2/issues/63 and that one was closed because this is more of a bug within Magento itself.
Might be best to read [the last comment](https://github.com/davidalger/capistrano-magento2/issues/63#issuecomment-423660202).

**Comment by PascalBrouwers** [comment]
Ah sorry, didn't see that one. You are right, it is best to leave it as it is.
