### ISSUE TITLE
Specify user that runs bin/magento?

### ISSUE THREAD

**Issue by cscd98** [davidalger/capistrano-magento2#114]
Our files get deployed with a **deploy** user but php runs as a **www-data** user.

This prevents www-data from writing to our files if php hacked etc.

When deploying via this gem, setup:db-schema:upgrade, magento:setup:db:data:upgrade, bin/magento -- app:config:import, magento:cache:flush etc. get run as our deploy user which means the files are generated using deploy, but I want them generated as the www-data user.

After deployment for example this is how it looks:

app/functions.php
```
-rw-r--r--  1 deploy deploy    419 Oct  3 12:58 functions.php
```

But when bin/magento is run by the gem, it creates permissions as so:

generated/code/Amasty/Shopby/Model/Layer/Filter
```
-rw-rw-r-- 1 deploy www-data 1116 Oct  3 13:00 ItemFactory.php
```

However, I would like files generated by bin/magento such as those in generated/ and var/ to be www-data:www-data

As php-fpm is run as www-data, is it still able to access these files as normal?

**Comment by davidalger** [comment]
> As php-fpm is run as www-data, is it still able to access these files as normal?

This completely depends on how the server in question is configured, way too many permissions scenarios for me to say.

What I would suggest looking at is using `setgid` permissions on the parent directory, and make sure the deploy user is a member of `www-data` group. If that doesn't work, perhaps add a custom command to your project configuration to run chown on the files.

Doing this is currently outside the scope of this tool, although there has been some discussion around a proposal that would allow accomplishing what you're dong here, I simply don't have the time nor purpose to implement it, but feel to take a look for ideas, etc.
https://github.com/davidalger/capistrano-magento2/issues/38#issuecomment-277267988
