### ISSUE TITLE
Cache warm task?

### ISSUE THREAD

**Issue by cscd98** [davidalger/capistrano-magento2#117]
e.g. magento:cache:warm https://www.xxx.com/some-page

Task would need to run after magento:cache:flush

You would need to be able to specify - host or ip, if IP supplied allow you to pass the host header (e.g. if you have load balanced servers), page to warm, optional sitemap?

**Comment by davidalger** [comment]
This is not something I have any intention of adding to this tool. Personally I think cache warming is a flawed approach to scaling, and it only works in a sub-set of deployment scenarios (such as blue/green, where the varnish instances are not live until blue/green instances are swapped into production use), and it would be rather difficult to implement in a fashion that would cover scenarios where it might be used in a flexible manner (or if something like Fastly is used, wouldn't even be possible to implement in this tool). See this from the varnish documentation though: 

> Concurrent backend requests for the same object are coalesced -- only one fetch is executed at a time, and the other pending fetches wait for the result (unless you have brought about one of the states described below in Uncacheable content). This is to prevent your backend from being hit by a "thundering herd" when the cached response has expired, or if it was never cached in the first place. If it turns out that the response to the first fetch is cached, then that cache object can be delivered immediately to other pending requests.

Varnish does a lot already to keep requests from flooding the backend when the cache is flushed. If you want to give a go implementing this on a per-project basis, look at adding a custom task in your project. I do this for other things by adding this line to `Capfile`

```ruby
# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
```

This allows defining custom tasks in any rake file in that directory and have them automatically included. An example from a real-life deployment scenario might look like the following:

```ruby
after 'magento:composer:install', 'magento:apply:patches' do
  on release_roles :all do
    within release_path do
      output = capture :find, "patches -maxdepth 1 -type f -name *.patch || true"
      output.split("\n").each do |patch_file|
        execute :git, "apply -v -p1 #{patch_file}"
      end
    end
  end
end
```

Note the way it's defining what it runs after. Change that to run after/before some other task that's run in the existing deployment flow, and your task will execute.
