### ISSUE TITLE
magento:cache:flush - task - does this also clear varnish cache?

### ISSUE THREAD

**Issue by cscd98** [davidalger/capistrano-magento2#118]
magento:cache:flush - task - does this also clear varnish cache?

```
01 php -f bin/magento -- cache:flush
      01 Flushed cache types:
      01 config
      01 layout
      01 block_html
      01 collections
      01 reflection
      01 db_ddl
      01 compiled_config
      01 eav
      01 customer_notification
      01 full_page
      01 config_integration
      01 config_integration_api
      01 target_rule
      01 codesocial_redis_cache
      01 config_webservice
      01 translate
      01 amasty_shopby
      01 vertex
```

Or do I need to run separately:
magento:cache:varnish:ban

**Comment by davidalger** [comment]
This would depend on whether or not Magento is configured to clear varnish. As long as you have the varnish cache hosts specified in Magento's `env.php` file, the Magento cache flush will send ban requests to varnish. Sometimes things like static files end up varnish without `X-Magento-Tags` headers though, and that (along with a need to privately support multiple Magento instances behind one varnish instance) is why there is buried in the module the rather undocumented `Magento:cache:varnish:ban` command, which was developed to support purging varnish using the `X-Pool` header which I add to all my varnish configs. This `X-Pool` is in the VCL in the Magento 2 repo now (I submitted a PR a while back), but originally it wasn't there and that is why this is undocumented behavior.

For the native Magento varnish purging, see devdocs for how to configure this, referencing the `--http-cache-hosts` on the `setup:config:set` command: https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands-deployment.html

For purging varnish hosts based on the `X-Pool` header you'll need to first add that header in Nginx, Apache, or whatever server you use to handle backend application requests and be sure your VCL handles purge requests based on this header value, and then configure the `:ban_pool` and `:varnish_cache_hosts` settings. See here for details on how they are used:
https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/tasks/magento.rake#L83-L102

An example from one of my old configs looks like this:
```ruby
set :ban_pools, ['prod']
set :varnish_cache_hosts, [
  '942791-admin1:6081',
  '942738-web5:6081',
  '942744-web6:6081',
]
```

The varnish cache hosts in the above example are internal hostnames on the cluster this was deploying to.
