### ISSUE TITLE
Sitemap symlink?

### ISSUE THREAD

**Issue by cscd98** [davidalger/capistrano-magento2#119]
The default symlink in capistrano-magento2 is pub/sitemaps. But magento seems to create sitemaps in sitemap folder in the root.

Is this a magento2 issue or is the wrong folder linked?

https://support.hypernode.com/knowledgebase/using-sitemap-xml-magento2/

**Comment by cscd98** [comment]
For now I have added:

```
# add magento 2 sitemap folder
append :linked_dirs, 'sitemaps'
```

**Comment by davidalger** [comment]
This gem links pub/sitemaps because best practice is to use `pub` as the webroot. Magento can be configured to publish sitemaps just about anywhere. The defaults here are based on the best-practice of using `pub` dir as the webroot.
