### ISSUE TITLE
Deploy in production but keep static

### ISSUE THREAD

**Issue by frangolacci** [davidalger/capistrano-magento2#125]
Hello,

first, thanks for you work !!

Is it possible to deploy code in production mode but not having to deploy static content again (so keep the one from the previous working release )?
Indeed, sometime we have code change which not involves html, css or image files.
So skipping the deploy:static will permit to gain a lot of time during deployment (but we have to get the previous static content)
I know we can disable the production mode ,so no static content deploy, but no di compile too and the shop will not be in production mode...

Thanks for your help

**Comment by davidalger** [comment]
@frangolacci Thanks for the question! Unfortunately no, this is not possible given how Capistrano works in general (i.e. not specific to this extension of Capistrano). When Capistrano deploys, it creates a new release directory. If we were to disable static content deploy on a given release, the static content simply be gone when the `current` symlink was updated to point to the new release directory.

If the time it takes to run static content deployment is ultimately what is of a concern here, I'd recommend considering the use of `:magento_deploy_themes` setting to limit the number of themes being generated on each deploy.
