### ISSUE TITLE
Should pub/static also be shared?

### ISSUE THREAD

**Issue by cscd98** [davidalger/capistrano-magento2#127]
For deployment purposes, some CSS/JS might be lost before cache clear.
Also for sharing between multiple servers on LB?

**Comment by davidalger** [comment]
`pub/static` should never be shared IMO. The contents of this directory is generated by the SCD process and sharing it between nodes is not recommended. Nothing in this path should ever be removed as part of a cache flush operation. The only content of `pub/static` that is not handled properly by the SCD properly is the `pub/static/_merged` dir and that is a core Magento bug (it's simply not generated on SCD as it should be). No intention of changing anything here within the confines of this gem, so I'm going to go ahead and close this out. If you want to share that dir amongst nodes, feel free to tackle it independently, but like I said…not recommended.
