### ISSUE TITLE
error deploying magento2.3.1

### ISSUE THREAD

**Issue by rizwanwakil2018** [davidalger/capistrano-magento2#129]
I am getting below error while deploying to production server.  

The contents from the "/var/www/html/releases/20190628211915/pub/static/adm  
  inhtml/Magento/backend/en_US/extjs/resources/css/ext-all.css" file can't be  
   read. Warning!file_get_contents(/var/www/html/releases/20190628211915/pub/  
  static/adminhtml/Magento/backend/en_US/extjs/resources/css/ext-all.css): fa  
  iled to open stream: No such file or directory 

if i run the php bin/magento setup:static-content:deploy -f on production server from release directory, it's works 

Need help please

**Comment by davidalger** [comment]
The above error is coming from the Magento application and isn't the result of anything this gem does (this gem pretty much connects via ssh and runs the same commands). If you haven't already resolved, might try looking through issues on the Magento github for possible causes.
