### ISSUE TITLE
Merge css on deployment

### ISSUE THREAD

**Issue by sebfie** [davidalger/capistrano-magento2#132]
Hello,

When deploying using this lib, my css/js are not merged. I am trying to find why ! I will keep it update to know if it's a bug or not!

**Comment by sebfie** [comment]
First observation. If I go to my project : 

```
rm -rf var/view_preprocessed/pub
php -f bin/magento -- setup:static-content:deploy
bin/magento cache:flush
```

My css are now merged !

**Comment by sebfie** [comment]
Why di:compile is launch before to set production mode?

https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/tasks/deploy.rake#L58

Why not to : 

```
invoke 'deploy:symlink:link_env_php'

if fetch(:magento_deploy_production)
   invoke 'magento:deploy:mode:production'
   invoke 'magento:setup:di:compile'
   invoke 'magento:setup:static-content:deploy'
   invoke 'magento:composer:dump-autoload' if fetch(:magento_deploy_composer)
end
```

**Comment by sebfie** [comment]
It was an issue of permission on my side. Sorry about that!

**Comment by davidalger** [comment]
@sebfie Glad you got it figured out! To answer the Q about why di:compile before production mode set, the gem supports dumping theme/i18n/design configuration to config.php to build without connection to the database. I've seen the call to `composer install …` nuke cache settings (why I have no clue, but disabling cache on high traffic site is incredibly painful). So when those things are dumped to config.php, the env.php file is removed and re-linked _after_ static content deploy, DI compile etc. If it were to link the env.php file _before_ running static content deploy / DI compile, then Magento will attempt connection to the database and redis cache opening the door for other side-effects during the build phase of the deployment.
