### ISSUE TITLE
capistrano not deploy latest files from latest revision

### ISSUE THREAD

**Issue by yattargor** [davidalger/capistrano-magento2#135]
Hello,
I'm a newbie of capistrano, and so i don't know if its my problem or a capistrano problem.
I can try to explain..
I use capistrano 3.11.2 and use it to deploy magento repo on one of my staging server.

Deployment process is all ok and magento instance run on staging server but every time I deploy, But capistrano only download some files from my master branch (I used default setup to deploy magento that I found here). (seems that capistrano only download initial commit and not further commit)
for example some images file not load and other file modification in various folder of magento project folder.

only for a test i try normal "git clone" command and I see that all files were downloaded from my local gitlab repository.

I don't know maybe I do something wrong in the process... or put some wring setup in capistrano config files.

Thank you in advance for your answer

**Comment by jaywilliams** [comment]
It depends on how you have your Capistrano configuration setup, but typically you have it pull from a shared (origin) Git repository.

So if you want your latest commits to be deployed, you must first `push` your code to your origin server, and have it deploy from that repo.

**Comment by yattargor** [comment]
Thank you for you answer.

I pushed all my code to my origin/master gitlab repo, infact is strange that during normal "git clone" command dowload all the files.

Today I notices another strange behaviour, I made various test and I noticed that at the beginning of the deploy process with capistrano some files are correct in /releases/<version_number> folder but before the end of the script deploy process files change (for example in project root i have .htaccess with one sentence for rewrite "Options +SymLinksIfOwnerMatch" and during deploy process become "Options +FollowSymLinks").

not so really where to bang your head, I tried them all.

If you can give me explanations about it you will be very grateful

Thank you in advance for you answer

**Comment by jaywilliams** [comment]
The default Magento 2 install overrides the .htaccess file when installing it. The only way to ensure custom tweaks are in place is to apply patches after M2 install, or configure your Apache config separately (e.g. in your global httpd.conf file)

If you're just getting started with Capistrano, I'd suggest setting up a very simple (non-Magento) test deployment, using just https://capistranorb.com/ and no other gems.

If you can get a basic, static HTML site working, then scale up and try working with Magento 2 deploy.

**Comment by yattargor** [comment]
Ok, thank you very much for your fast answer.
One other question and after that maybe is better that I follow your advice and try example deploy with https://capistranorb.com/

So like you say is possible that some files that I have in my remote repo after deploy with capistrano-magento2 are deleted?
for example in pub/media (in my remote repo) I have some files that I setup in my dev env but after deploy magento with capistrano-magento2 in my staging env not appear, is possible?

Thank you in advance for your answer

**Comment by jaywilliams** [comment]
`pub/media` is a [shared (symlinked) directory](https://capistranorb.com/documentation/getting-started/structure/). You really need to read up on the Capistrano docs, figure out how the system works, and get a static HTML site deploying, and once you get a simple example working, you can expand to Magento 2.

Magento is a very complex system, and therefore the deploy is equally complex. This Ruby gem does a great job making it easier to work with, but if you don't understand how Capistrano works, it won't help you very much, as it simply builds upon Capistrano itself.

There are lots of resources, and even paid video tutorials out there which can teach you how to use Capistrano. Search around, find some which look good, and enjoy.

**Comment by yattargor** [comment]
Tahnk you very much for your time and your explaination!
I will follow your advices.

Thank you
