### ISSUE TITLE
Support Baler in the deployment process

### ISSUE THREAD

**Issue by dverkade** [davidalger/capistrano-magento2#140]
With Magento now offering a module called Baler for javascript bundling it would be nice to have this supported within the deployment as well. We don't have to add deployment steps manually if this is supported out of the box.

**What needs to be done**

- Add task to run baler in the deployment process.
- Make step configurable so that it can be turned on and off depending on project.

**What is out of scope**

- Installing Baler on the environment
- Making other changes in the deployment process.

**Comment by valguss** [comment]
We've done similar with magepack and have just added a task like:

```
namespace :magepack do
  desc "Bundle JS"
  task :bundle do
    on release_roles :all do
      within release_path do
        execute *%w[node ./node_modules/magepack/cli.js bundle]
      end
    end
  end
end

after "magento:setup:static-content:deploy", "magepack:bundle"
```

**Comment by dverkade** [comment]
Since Baler is abandoned (more information here: https://github.com/magento/devdocs/pull/7876 ) I'll close this issue.

**Comment by jerrylopez** [comment]
@valguss did you run into any issues when using this task to build the bundles using Magepack? One issue that I'm currently running into is that the minified version of the files aren't generated. It also seems to take significantly less time to bundle during deployment than running manually which I'm thinking might be an issue as well

**Comment by jerrylopez** [comment]
Just an update to my last question. I figured out the issue. If you're using zero-side effect deployments you need to set up your bundling config settings in the `app/etc/config.php` since `env.php` is removed during deployment.
