### ISSUE TITLE
Run magento command inside docker

### ISSUE THREAD

**Issue by nntoan** [davidalger/capistrano-magento2#142]
Hi there,

I'm wondering if it's possible to run magento command with docker exec? And what is the right configuration for it in capistrano-magento2?

Thanks,

**Comment by davidalger** [comment]
@nntoan I'm not sure that using Capistrano to deploy into docker environments is a common pattern, and it's not one that I've tried, so I can't really be of help. There is info from others who have done this, including different backends for SSH Kit it seems to run stuff in docker. Best bet is probably going to be to do a little searching on the topic to see what's out there at a more generic level of Capistrano and SSH Kit than specific to this gem, which only provides the Magento 2 tasks of the deployment lifecyle: https://www.google.com/search?client=firefox-b-1-d&q=capistrano+ssh+kit+docker+exec
