### ISSUE TITLE
Do not run show pending updates when capistrano is outside magento git repo

### ISSUE THREAD

**Issue by dooblem** [davidalger/capistrano-magento2#145]
Hello,

From my understanding, the "show pending update" feature is only working if capistrano is in the same git repo as Magento.

I intend to have capistrano in a separate git repository. In that case it's not working. It's showing me an error at the very beginning, running a git fetch origin in the capistrano directory. Except that my capistrano is not in a git repo (yet).

When running a deploy:
```
...
** Execute deploy:pending:log
00:00 deploy:pending:log
      01 git fetch origin
      01 fatal: 'origin' does not appear to be a git repository
      01 fatal: Could not read from remote repository.
      01
      01 Please make sure you have the correct access rights
      01 and the repository exists.
#<Thread:0x000055916528ec08@/var/lib/gems/2.5.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /var/lib/gems/2.5.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
...
```
Capistrano is trying to run git fetch origin locally.

Maybe I'm missing something, but my understanding is that this feature should not be called in my case.

I commented the require 'capistrano/magento2/pending' line in Capfile and all is fine now.

A simple improvement would be to add in the README something like "add this line" only if your capistrano is in the same repo as Magento.

Thanks in advance,
Marc

**Comment by davidalger** [comment]
> I commented the require 'capistrano/magento2/pending' line in Capfile and all is fine now.

Sounds like you figured out. Yes, that line should either be commented or removed when choosing not to tie in with the capistrano-pending gem, as I don't believe it will work when running capistrano tooling from a different repository.

As this is not a very common scenario, I'm going to leave the README as-is given it does currently imply this line may removed in the section dedicated to covering what it does: https://github.com/davidalger/capistrano-magento2#pending-changes-support Should anyone else encounter the issue, this issue will perhaps serve them well though, so appreciate you sharing the use-case!
