### ISSUE TITLE
Can't install 'capistrano/magento2/cachetool'

### ISSUE THREAD

**Issue by moElwan** [davidalger/capistrano-magento2#147]
Hello David,
when I try to install the cachetool as mentioned in https://github.com/davidalger/capistrano-magento2#php-opcache-reset I get an error `Could not find a valid gem 'capistrano/magento2/cachetool' (>= 0) in any repository`
![image](https://user-images.githubusercontent.com/1895158/89285641-07d02d00-d651-11ea-8c70-58532c8fcad8.png)

should we use `capistrano-cachetool`? or I'm missing something please? 

Thanks for all the great work

**Comment by davidalger** [comment]
@moElwan Read the docs a bit more carefully. You won't see any mention of gem install, as this is not a gem:

> To use this, include `require 'capistrano/magento2/cachetool'` in your `Capfile` and make sure there is an `/etc/cachetool.yml` or `/var/www/html/.cachetool.yml` (assuming `:deploy_to` points at `/var/www/html`) file configured with contents like the following: …

The reference to `require 'capistrano/magento2/cachetool` in your `Capfile` is loading an additional rake file from the `capistrano-magento2` gem. It only works if, per the referenced documentation, the `cachetool` tool is already installed and configured such that if you run SSH into the server and run `cachetool opcache:status` from the path in which you're deploying you get a response. For example:

![Screen-Shot-2020-08-04-08-33-34 34-HacwKlU6jwLG](https://user-images.githubusercontent.com/658281/89300229-7e5b3380-d62d-11ea-8813-e46a6f2a6e06.png)

**Comment by moElwan** [comment]
@davidalger thanks a lot for the quick reply, that's good news thank you 
yeah I've all set and ready on production as mentioned
I will test deploying as is now
