### ISSUE TITLE
[enhancement] Deploy on multiple fronts without recompiling everything on each machine

### ISSUE THREAD

**Issue by dooblem** [davidalger/capistrano-magento2#148]
Actually, when deploying on several web fronts, everything gets compiled on each front (composer+di:compile+static compile).

I believe this is not optimal. That's why on several projects I have patched a bit the capistrano-magento2 module in order to:
* compile the assets only on the primary (possibly the primary can be a regular web front, or a false batch front with no traffic used only to compile assets)
* once assets compiled, use rsync from other web fronts in order to get the generated release directory form the primary

I'm pasting my patch bellow (this is from an old version of the module).

I would like to make things a bit cleaner, and possibly have your opinion if you think this feature is worth including in the module.

In deploy.rake, I just added a rsync_to_other_releases task. I also could have put this into a rake file in my local capistrano repo, with a before/after hook. I think it would be handy to have it inside capistrano-magento2 module, but not absolutely necessary.

In magento.rake, I patched all the "on release_roles :all" in order to run things only on the primary. For this I do not see any other easy way to achieve this. What would be nice is something with a custom property like "on release_roles(:all, exclude: :no_compile)

Thanks in advance !

```
commit d2cfbfe4224fb455ed647aa53a2cb21c8fb43a42
Author: Marc MAURICE <mmaurice@clever-age.com>
Date:   Mon Feb 18 15:00:08 2019 +0100

    Changed release creation system on other nodes.
    Other nodes get their release from primary via rsync.

diff --git a/lib/capistrano/tasks/deploy.rake b/lib/capistrano/tasks/deploy.rake
index e76542c..179fa29 100644
--- a/lib/capistrano/tasks/deploy.rake
+++ b/lib/capistrano/tasks/deploy.rake
@@ -21,7 +21,15 @@ namespace :deploy do
     end
   end
 
+  task :rsync_to_other_releases do
+    on release_roles(:all, primary: nil), in: :sequence do
+      primaryname = primary(fetch(:magento_deploy_setup_role)).hostname
+      execute :rsync, "-a", "--delete", "#{primaryname}:#{release_path}/", "#{release_path}/"
+    end
+  end
+
   task :updated do
+
     invoke 'magento:deploy:verify'
     invoke 'magento:composer:install' if fetch(:magento_deploy_composer)
     invoke 'magento:deploy:version_check'
@@ -32,6 +40,9 @@ namespace :deploy do
       invoke 'magento:setup:di:compile'
       invoke 'magento:composer:dump-autoload' if fetch(:magento_deploy_composer)
     end
+
+    invoke 'deploy:rsync_to_other_releases'
+
     invoke 'magento:setup:permissions'
     invoke 'magento:maintenance:check'
     invoke 'magento:maintenance:enable' if fetch(:magento_deploy_maintenance)
diff --git a/lib/capistrano/tasks/magento.rake b/lib/capistrano/tasks/magento.rake
index c60290d..83b6c75 100644
--- a/lib/capistrano/tasks/magento.rake
+++ b/lib/capistrano/tasks/magento.rake
@@ -105,7 +105,7 @@ namespace :magento do
     desc 'Run composer install'
     task :install => :auth_config do
 
-      on release_roles :all do
+      on primary fetch(:magento_deploy_setup_role) do
         within release_path do
           composer_flags = '--prefer-dist --no-interaction'
 
@@ -131,7 +131,7 @@ namespace :magento do
     desc 'Run composer dump-autoload'
     task 'dump-autoload' do
 
-      on release_roles :all do
+      on primary fetch(:magento_deploy_setup_role) do
         within release_path do
           composer_flags = '--no-interaction'
 
@@ -167,7 +167,7 @@ namespace :magento do
     namespace :mode do
       desc "Enables production mode"
       task :production do
-        on release_roles(:all), in: :sequence, wait: 1 do
+        on primary fetch(:magento_deploy_setup_role) do
           within release_path do
             execute :magento, "deploy:mode:set production --skip-compilation"
           end
@@ -185,7 +185,7 @@ namespace :magento do
     end
 
     task :version_check do
-      on release_roles(:all), in: :sequence, wait: 1 do
+      on primary fetch(:magento_deploy_setup_role) do
         within release_path do
           _magento_version = magento_version
           unless _magento_version >= Gem::Version.new('2.1.1')
@@ -299,7 +299,7 @@ namespace :magento do
     desc 'Sets proper permissions on application'
     task :permissions do
-      on release_roles :all do
+      on primary fetch(:magento_deploy_setup_role) do
         within release_path do
           execute :find, release_path, "-type d ! -perm #{fetch(:magento_deploy_chmod_d).to_i} -exec chmod #{fetch(:magento_deploy_chmod_d).to_i} {} +"
           execute :find, release_path, "-type f ! -perm #{fetch(:magento_deploy_chmod_f).to_i} -exec chmod #{fetch(:magento_deploy_chmod_f).to_i} {} +"
@@ -315,7 +315,7 @@ namespace :magento do
     namespace :di do
       desc 'Runs dependency injection compilation routine'
       task :compile do
-        on release_roles :all do
+        on primary fetch(:magento_deploy_setup_role) do
           within release_path do
             output = capture :magento, 'setup:di:compile --no-ansi', verbosity: Logger::INFO
 
@@ -331,7 +331,7 @@ namespace :magento do
     namespace 'static-content' do
       desc 'Deploys static view files'
       task :deploy do
-        on release_roles :all do
+        on primary fetch(:magento_deploy_setup_role) do
           _magento_version = magento_version
 
           deploy_themes = fetch(:magento_deploy_themes)
```

**Comment by davidalger** [comment]
Thanks for sharing the solution used in your scenario. Not going to apply the patches directly, as I don't think it fits the general use-case super well as-implemented and it also has implications from an SSH access perspective (rsync from one target to another requires port 22 be open between targets, which isn't always the case).

Artifact based deployment should be possible using this gem without any modifications, in the context of a pipeline which built the artifact, pushed it to an artifact git repository, then deployed from that with SCD and DI compilation disabled so the built artifact (commit in the artifact repository) is deployed as-is. Given this, I'm going ahead and marking this one as closed as I have neither the use-case nor time to implement something like this myself here (to get it right, it will take a lot of time and testing to make sure it won't disrupt existing use-cases)

**Comment by dooblem** [comment]
Hello @davidalger . Thanks for your reply.

Maybe I was not very clear.

> In magento.rake, I patched all the "on release_roles :all" in order to run things only on the primary. For this I do not see any other easy way to achieve this. What would be nice is something with a custom property like "on release_roles(:all, exclude: :no_compile)

In fact I do not need the patch above to be applied.

What would be great is just having a :no_compile property or similar, in order to be able to disable asset compiling on some fronts only.

Such a patch would be way simpler and less intrusive. Would you be willing to accept such pull request ?

Thanks in advance,
Marc
