### ISSUE TITLE
Add option to skip maintenance mode

### ISSUE THREAD

**Issue by cscd98** [davidalger/capistrano-magento2#15]
@davidalger would it be possible to make this a setting to skip magento:composer:install.

Also is it possible to skip maintenance mode? This causes an exception for me due to a bug in data migration tool

**Comment by davidalger** [comment]
@craigcarnell Saw your comment on the other issue and began thinking of it, but forgot to reply and let you know I was going to add it :)

Just added these two settings this morning and included them in the updated 0.4.0 tagged release. There are details on these in the README under [Deploy Settings](https://github.com/davidalger/capistrano-magento2#magento-deploy-settings).

Let me know if this does/doesn't address your issues. Thanks for the suggestion!!

**Comment by cscd98** [comment]
@davidalger Thank you 👍
