### ISSUE TITLE
Deploy shuts off maintenance mode

### ISSUE THREAD

**Issue by giacmir** [davidalger/capistrano-magento2#16]
If a deploy is made when magento is in maintenance mode then is set back online. It would be useful to detect the current application maintenance status and disable maintenance mode only if it was already disabled at the beginning of the deploy process.

**Comment by davidalger** [comment]
@giacmir Good call! I'll plan on adding this to a patch release soon…

**Comment by davidalger** [comment]
@giacmir Wanted to let you know… I was going to try and get this done before I go on holiday for 3 weeks, but time did not allow for it. I'm getting married this Saturday and won't back in the saddle with work or any Magento related stuff until September. :) So it might be a while longer before I can personally get to adding this to the gem.

**Comment by giacmir** [comment]
@davidalger I'm very happy to wait for such a cheerful cause and best wishes for your family life!

**Comment by davidalger** [comment]
@giacmir I'm happy to report that after this long amount of time (sorry about the wait) I have finally made the time to implement this. I did the implementation in the same maintenance mode check routine used to accomplish zero-down deployments. See the above commit for details. I'll be including this in the next release when I push it out (I expect will be in the next few days)

**Comment by davidalger** [comment]
This has been published as part of v0.8.1.

Thanks again for the suggestion!
