### ISSUE TITLE
Terminal notifier outputs garbage to screen in linux

### ISSUE THREAD

**Issue by giacmir** [davidalger/capistrano-magento2#19]
Hello, 

I'm using your gem in linux (with zsh shell) and at the end of a deploy terminal notifier spits out some garbage text (see screenshot).

![screenshot](https://cloud.githubusercontent.com/assets/447940/18128511/62f1e6c8-6f86-11e6-861c-0d0b47e8aaa0.png)

Also, terminal notifier outputs the same even in other unrelated commands I call (eg, vagrant or ansible). Since it is not essential can the dependency be removed? I tried to google around to find some solutions but can't find anything.

**Comment by erikhansen** [comment]
@giacmir Did you add the line suggested by the [Terminal Notifier on OS X](https://github.com/davidalger/capistrano-magento2#terminal-notifier-on-os-x) section of the readme? If so, you should remove the `require 'capistrano/magento2/pending'` line from your `Capfile`.

**Comment by giacmir** [comment]
I didn't add that line... the problem is that if I have that gem installed I have this output not only on capistrano deploy, but even when issuing other commands (like "vagrant up"). I have to uninstall the gem, the reinstall it every time I have to deploy something. (or use capistrano through docker)

**Comment by erikhansen** [comment]
@giacmir Off the top of my head, I don't know what to tell you. Maybe @davidalger will have a suggestion for how to proceed, although it will likely be next week before he's able to respond.

**Comment by davidalger** [comment]
@giacmir I cannot reproduce this issue. When I attempt to run capistrano from within a CentOS vm I use for development, a warning shows up (shown in following example), but only if I explicitly include the terminal-notifier file via `require 'capistrano/magento2/notifier'

```
[vagrant@dev-web70]/sites/m2.cap/tools/cap% cap web70 deploy
...
14:26 deploy:log_revision
      01 echo "Branch master (at 3aee55cea802e487293b0c37636d041a438c6245) deployed as release 20160902215207 by vagrant" >> /sites/m2cap.demo/revisions.log
    ✔ 01 vagrant@dev-web70 0.142s
terminal-notifier is only supported on Mac OS X 10.8, or higher.%
[vagrant@dev-web70]/sites/m2.cap/tools/cap%
```

My gut tells me that something is messed up with rvm permissions or something, as the check for OS / environment by the terminal-notifier gem has been implemented for years, allowing it to merely display the above warning when the OS is wrong.

What does this command report back to you?

```
ruby -e 'puts RbConfig::CONFIG["host_os"]'
```

On my linux install it reports `linux-gnu` and on OS X reports `darwin14.5.0` - the gem is checking this value to case the notice that it displays.

I'm looking at removing the dependency, and finding out what using it will look like if it's not listed in the gem spec, but it might still be worth checking into the permissions of your rvm setup if that's the underlying culprit. :)

**Comment by giacmir** [comment]
Thanks for your answer

```
ruby -e 'puts RbConfig::CONFIG["host_os"]'
```

reports `linux-gnu`

I tried to run `rvm --fix-permissions` and it did something... I will let you know if this solves the issue.

**Comment by giacmir** [comment]
Nothing to do, I tried both to fix permission in nvm and to upgrade to latest 2.1 ruby but still have screen garbage. Probably is some strange connection with zsh.

**Comment by giacmir** [comment]
Tried to submit this issue as a bug to the terminal-notifier repo. They closed saying that it is not supposed (obviously) to be used under linux.

https://github.com/julienXX/terminal-notifier/issues/184

**Comment by davidalger** [comment]
@giacmir I have decided to remove the hard dependency and updated the README to reflect this. It will be published in the next version. Thanks for hanging in there!

**Comment by davidalger** [comment]
@giacmir This should be taken care of in release 0.6.0. Thank you for your patience!
