### ISSUE TITLE
Add ability to exclude certain themes from static compilation

### ISSUE THREAD

**Issue by erikhansen** [davidalger/capistrano-magento2#20]
Magento 2.1.1 added a number of new flags to the `bin/magento setup:static-content:deploy` command:

![html -bash 133x80-zrkta](https://cloud.githubusercontent.com/assets/129031/18140565/b2804438-6f7b-11e6-99db-d142e05cd7cb.png)

Since it is now possible to exclude certain themes from the static compilation, I'd recommend adding a `:magento_deploy_exclude_themes` argument that will accept an array of themes to exclude. 

For example, this:

```
set :magento_deploy_exclude_themes, ['Magento\blank', 'Magento\luma', 'ClassyLlama\basetheme']
```

Would result in this command being run:

```
bin/magento setup:static-content:deploy --exclude-theme="Magento/blank" --exclude-theme="Magento/luma" --exclude-theme="ClassyLlama/basetheme"
```

Adding this feature will reduce the deployment time significantly. As a point of reference, on a recent deployment of a Magento 2.1.0 site with 6 themes (only 3 of which needed to be compiled), the static asset compilation to 8:50m out of the 15:15m deploy time. If three of those themes were not compiled, the total compilation would have been reduced to around 11 minutes.

**Comment by erikhansen** [comment]
I just learned that 2.1.1 also added support for parallel asset compilation, so the value in excluding themes from compilation is minimal. As a result, I don't think adding this feature is worth the effort. Closing this issue.

**Comment by davidalger** [comment]
Agreed, probably not worth the effort, but if someone does want it and submitted a PR I would probably accept it.
