### ISSUE TITLE
Themes defined in "magento_deploy_themes" not being compiled

### ISSUE THREAD

**Issue by amansilla** [davidalger/capistrano-magento2#26]
I'm currently using magento 2.1.1 and set the `magento_deploy_themes` to `['Vendor/theme', 'Magento/backend']` but during static content compilation the `--themes` option is still missing, see result:

`/usr/bin/env php -f bin/magento -- setup:static-content:deploy en_US en_GB de_DE| stdbuf -o0 tr -d .`

**Comment by davidalger** [comment]
@amansilla What version of the gem do you have installed? That setting needs the latest version 0.5.0 which I tagged and pushed up to ruby gems yesterday. You can find out what version(s) you have installed by running the following command in your shell:

```
gem list capistrano-magento2
```

I put the line `set :magento_deploy_themes, ['Magento/blank', 'Magento/backend']` in my test configuration then deployed a 2.1.1 configuration and the themes were properly set as expected in the run:

```
00:49 magento:setup:static-content:deploy
      01 touch /home/vagrant/sites/m2cap.demo/releases/20160909145126/pub/static/deployed_version.txt
    ✔ 01 vagrant@dev-web70 0.133s
      02 php -f bin/magento -- setup:static-content:deploy en_US -t Magento/blank -t Magento/backend | stdbuf -o0 tr -d .
    ✔ 02 vagrant@dev-web70 95.940s
      03 php -f bin/magento -- setup:static-content:deploy en_US -t Magento/blank -t Magento/backend --no-javascript --no-css --no-less --no-images --no-fonts …
    ✔ 03 vagrant@dev-web70 1.366s
```

**Comment by amansilla** [comment]
Thx @davidalger my mistake, I didn't realize that functionality was only in the last release available. After upgrade to the version 0.5.0 everything is working as expected. Great job :wink:.
