### ISSUE TITLE
If setup:upgrade fails, site remains in maintenance mode

### ISSUE THREAD

**Issue by erikhansen** [davidalger/capistrano-magento2#27]
If the `bin/magento setup:upgrade` command fails, the site will remain in maintenance mode even after Capistrano is finished running. This results in a non-atomic deployment when there are errors with `setup:upgrade`. Example screenshot:

![14-49-14 cap -bash 107x81-6yh0t](https://cloud.githubusercontent.com/assets/129031/18400708/b0caf318-769c-11e6-955a-8f67e67d07da.png)

It seems like it would make sense for the `capistrano-magento2` Gem to be smart enough to take this scenario into account and take the site out of maintenance mode if `setup:upgrade` fails.

I _was_ able to use `cap stage deploy:rollback` to successfully rollback to a previous working release.

**Comment by davidalger** [comment]
@erikhansen This is not a matter of atomicity. An atomic deployment means the deploy is done in such a way that 100% of the online application is in-synch with the other parts. 

Is there a reason why you believe a failure on the database upgrade process should not halt the process and require manual effort to resolve? There is no way for the deploy tool to rollback any changes done by setup:upgrade before a reported failure, and also no way to know if the previous release will continue to work with the database in a failed upgrade state.

**Comment by erikhansen** [comment]
@davidalger Oh, great point. In my specific example above, the `setup:upgrade` didn't change anything about the DB structure that would have caused problems with a rollback, but you make a great point that this can't be guaranteed. So it's better to leave the site in maintenance mode than to rollback and cause further problems and/or site errors that are displayed to users. Closing this ticket.
