### ISSUE TITLE
DB Upgrade Memory Limit

### ISSUE THREAD

**Issue by mttjohnson** [davidalger/capistrano-magento2#39]
We noticed an instance of upgrading a magento site from 2.0 to 2.1 caused a lot more work for the db upgrade process and that step in the deployment tasks failed because we hit a PHP memory limit. We were able to restore a database backup and run the db upgrade manually on the server passing in an option on the command line to increase the memory limit so setup:upgrade would complete successfully.

Most deployments have never had any problems, but the update between 2.0 and 2.1 was more extensive than most on the db upgrade.

Command line execution of php on the server had a memory_limit of 1G
php -i | grep memory_limit
memory_limit => 1G => 1G

Some people have suggested removing the memory limit on the setup:upgrade call like:
php -d memory_limit=-1 bin/magento setup:upgrade

Is that something that should be in the capistrano module's call to setup:upgrade (or related db upgrade calls), or do you think that's something better left to changing the system default to be above 1G to avoid this in the future?

**Comment by davidalger** [comment]
As this is the only case I've heard of this being a problem, I'm going to go ahead and close this out. My recommendation would be ensure the memory_limit on the CLI is set high enough for the upgrade process to run when doing a major version upgrade, as implementing a custom memory limit for that one command would be rather tricky.

**Comment by sfblaauw** [comment]
Hi! Just in case somebody need it

`SSHKit.config.command_map[:magento] = "/usr/bin/env php -d memory_limit=-1 -f bin/magento --"`
