### ISSUE TITLE
Deploy from custom branch and check for conflicting branches

### ISSUE THREAD

**Issue by erikhansen** [davidalger/capistrano-magento2#40]
Feature suggestion:

1. Add ability to specify a different branch to be checked out using a command like this:
    ```
    BRANCH=feature/custom-feature bundle exec cap stage deploy 
    ```
    
2. Add a check to prevent different branches from being checked out by different users.

See this article for reference implementation for both of the above items: https://firmhouse.com/blogdeploying-branches-with-capistrano/

**Comment by davidalger** [comment]
@erikhansen 

> Add ability to specify a different branch to be checked out using a command like this:

This is normally done in the project cap configs and wouldn't belong being implemented in this gem. All you need is the following line in your deploy.rb (or <stage>.rb):

``` ruby
set :branch, ENV['BRANCH'] || "master"
```

> Add a check to prevent different branches from being checked out by different users.

I'll consider adding this as an optional function of the gem. It's something that probably should really be implemented in a separate gem which is Magento 2 agnostic though.

**Comment by erikhansen** [comment]
@davidalger Thanks for that one-liner.

Ok.

**Comment by davidalger** [comment]
No plans to do this. The functionality is targeting a specific (and infrequent use-case) which is not unique to Magento 2. Putting it in this gem (even as optional) really doesn't make much sense, and speaking from the Classy Llama side of things, not something I'd encourage within our org beyond having the BRANCH switch at this time.
