### ISSUE TITLE
Some setup:di:compile errors not reported

### ISSUE THREAD

**Issue by erikhansen** [davidalger/capistrano-magento2#41]
This issue is a similar problem to the one reported in #25. It is also somewhat related to #35. 

Here is an example screenshot demonstrating the problem:
![17-27-55 new message-cjlba](https://cloud.githubusercontent.com/assets/129031/20199161/572b61be-a76e-11e6-846e-c8406adf6587.png)

I'm using Magento EE 2.1.2. Errors generated during `setup:di:compile` are not being reported when deploying. The errors are essentially being ignored and the deployment continues as if nothing happened. 

I think the problem is that we assumed that Magento 2.1.x fixed the issue where `setup:di:compile` and `setup:static-content:deploy` were not returning non-zero exit codes upon failure, but this is not _always_ the case. While the https://github.com/magento/magento2/pull/3189 PR _did_ fix the return code issue in many situations, it looks there are certain "soft" errors that don't result in error codes: https://github.com/magento/magento2/blob/1ade3b769a937f19682bbbe4e51b6c956147952f/setup/src/Magento/Setup/Module/Di/Compiler/Log/Writer/Console.php#L72

**Comment by davidalger** [comment]
Released in 0.5.6.
