### ISSUE TITLE
Idea: "Composer install? Why not copy previous_version/vendor + composer update?"

### ISSUE THREAD

**Issue by avra911** [davidalger/capistrano-magento2#48]
Hi,

This is just an idea, not even sure it could work.
My question is why not copying vendor folder from previous version and then composer update instead of composer install? If works could be faster :)

Best regards,
Razvan

**Comment by danslo** [comment]
Multiple reasons.

1) Composer packages are cached anyway.
2) install will use lock file to install exact version of dependencies,
it's not desirable to run update on deployment targets

**Comment by avra911** [comment]
Alright, that makes sense now!

Thank you for feedback!
