### ISSUE TITLE
Can't connect to local MySQL

### ISSUE THREAD

**Issue by anthonyherve** [davidalger/capistrano-magento2#52]
Hello,

I have a problem when I deploy my Magento2 application, during this command.
/usr/bin/env php -f bin/magento -- setup:static-content:deploy en_US

I have following error : 
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)

I have a database server separated from my web server, and I see that symlink to env.php file is not done when setup:static-content:deploy is launched.

Is there a way to do symlinks before launching magento commands ?

Thank you for your help.

**Comment by davidalger** [comment]
@anthonyherve The sym-linking of directories and files is something capistrano takes care of before `deploy:updated` runs, which is the task which the gem's built-in deploy routine hooks into for running these M2 specific commands.  I'm a bit unclear on how you could run into this file not being linked when this command being run. What does your Capfile look like? Does it include everything found in example under [usage in the README](https://github.com/davidalger/capistrano-magento2#usage)?

**Comment by anthonyherve** [comment]
@davidalger Thank you for your answer.
Here is my Capfile

```ruby
# Load DSL and set up stages
require 'capistrano/setup'

# Include default deployment tasks
require 'capistrano/deploy'

# Load Magento deployment tasks
require 'capistrano/magento2/deploy'

# Include local git with RSYNC scm
import "lib/capistrano/rsync.rb"

# Load custom tasks from `lib/capistrano/tasks' if you have any defined
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }`
```

I see I have this line in addition to config (https://github.com/davidalger/capistrano-magento2#usage).
require 'capistrano/deploy'

Do you think my error can be from this ?

Thank you.

**Comment by anthonyherve** [comment]
It's finally OK for me. I have a problem with my env.php.
Sorry for disturbing. Thank you for your lib. :-)
