### ISSUE TITLE
Capistrano 3.7.1 requires explicit inclusion of the Git SCM plugin

### ISSUE THREAD

**Issue by erikhansen** [davidalger/capistrano-magento2#53]
I just upgraded one of my projects to Capistrano 3.7.1. After updating the `lock '3.6.1'` line in my `tools/cap/config/deploy.rb` to `lock '3.7.1'` and running `bundle exec cap stage deploy`, I got this deprecation warning:

```
[Deprecation Notice] Future versions of Capistrano will not load the Git SCM
plugin by default. To silence this deprecation warning, add the following to
your Capfile:

    require "capistrano/scm/git"
    install_plugin Capistrano::SCM::Git
```

The deployment continued without a problem, but this project's readme should be updated to include those two configuration lines in the `Capfile`.

**Comment by davidalger** [comment]
@erikhansen Would you like to submit a PR so the contribution will be properly attributed?

**Comment by erikhansen** [comment]
@davidalger Submitted a PR: https://github.com/davidalger/capistrano-magento2/pull/54

**Comment by davidalger** [comment]
PR merged to develop. It'll hopefully make it into master soon. Closing.
