### ISSUE TITLE
composer install is executed twice under magento:composer:install

### ISSUE THREAD

**Issue by wintermute-84** [davidalger/capistrano-magento2#76]
Is there a reason for this?

The first one is 
`/usr/local/bin/composer install --prefer-dist --no-interaction --optimize-autoloader 2>&1` 
and the second one is with `--no-dev` flag

The problem with this approach is that composer install hooks can't be used.
Using hooks is useful for scripts to be executed locally without capistrano.  

Thank you for any input

**Comment by davidalger** [comment]
@Dukeofvampires Sorry about the delayed reply here. There is a reason for it :) Use of the --no-dev flag requires using Magento 2.1.1 or later, and although I do not recall what it was, it had to do with I didn't have a way to reliability tell ahead of time if I should or should not use --no-dev at the time.

All that said…I'm working on v0.7.0 of this gem, updating a few things to support deployment of 2.2-RC2.0 and will be removing the duplicate composer install command as part of that work and then supporting Magento version 2.1.1 or later only from v0.7.0 of this gem onward.

You should see v0.7.0 of this gem hit soon. :)

**Comment by wintermute-84** [comment]
Hi David, I appreciate your work.
We are waiting for the new release then.
