### ISSUE TITLE
Fix Magento version comparison for 2.2.0-rc

### ISSUE THREAD

**Issue by PascalBrouwers** [davidalger/capistrano-magento2#79]
I cannot complete the deployment because of this error:
`ArgumentError: Malformed version number string 2.2.0-rc`

This happens with the latest version (0.7.1). The target Magento installation is running version 2.1.8 which `bin/magento -- -V --no-ansi` detects correctly.

It seems the issue comes from here: https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/magento2.rb#L36

**Comment by PascalBrouwers** [comment]
I think it needs to be in the format of 2.2.0.rc but I'm not sure how the compare it to the Magento version 2.2.0-rc then. Maybe with a replace on `-` ?

**Comment by PascalBrouwers** [comment]
Hmm, no. That's not correct because 2.2.0.rc means that 'rc' is then the metadata tag. Looks like we need to resort to a gem that can handel SemVer versions.

**Comment by davidalger** [comment]
@PascalBrouwers What version of Ruby are you running on? This is supported by Gem::Version and works in all my testing, so I'm wondering if it is a version discrepancy. See following from my shell:

```bash
dalger:12:41 PM:~$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
dalger:12:41 PM:~$ ruby -e 'puts puts Gem::Version.new("2.2.0-rc")'
2.2.0.pre.rc

dalger:12:41 PM:~$ ruby -e 'puts puts Gem::Version.new("2.2.0-rc21")'
2.2.0.pre.rc21

dalger:12:41 PM:~$ ruby -e 'puts puts Gem::Version.new("2.2.0")'
2.2.0

dalger:12:41 PM:~$ ruby -e 'puts puts Gem::Version.new("2.2.0-beta1")'
2.2.0.pre.beta1

```

Using the ruby installed natively on OS X (older version) I can reproduce that error:

```shell
dalger:12:43 PM:~$ /usr/bin/ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
dalger:12:43 PM:~$ /usr/bin/ruby -e 'puts puts Gem::Version.new("2.2.0-rc21")'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb:191:in `initialize': Malformed version number string 2.2.0-rc21 (ArgumentError)
	from -e:1:in `new'
	from -e:1:in `<main>'
dalger:12:43 PM:~$ /usr/bin/ruby -e 'puts puts Gem::Version.new("2.2.0-beta1")'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb:191:in `initialize': Malformed version number string 2.2.0-beta1 (ArgumentError)
	from -e:1:in `new'
	from -e:1:in `<main>'
dalger:12:43 PM:~$ /usr/bin/ruby -e 'puts puts Gem::Version.new("2.2.0.rc")'
2.2.0.rc

dalger:12:43 PM:~$ /usr/bin/ruby -e 'puts puts Gem::Version.new("2.2.0.pre.rc")'
2.2.0.pre.rc

```

This could (it seems) be worked around (at least on ruby 2.0.x) by changing the format of the version Magento CLI provides and also changing the `-rc` in the version I'm comparing against to use `.pre.rc` instead. I'm hesitant to do that though, as I've not tested _anything_ with older versions of ruby.

I'm trying to determine a simple way to find out where the support for the hyphen in versions was introduced.

**Comment by PascalBrouwers** [comment]
@davidalger I did test it on OS X. Let me see if I can update Ruby to see if the issue goes away.

**Comment by davidalger** [comment]
PascalBrouwers Do you use https://brew.sh? That's the simplest way I know to install multiple versions of Ruby on OS X. A`brew search ruby` will show you the various ruby versions available (or just `brew install ruby` to get the latest). I just installed 2.1 in addition to the OS X default 2.0 and the latest (2.4) which I already had installed. It looks like Gem::Version works with the `-rc` in ruby 2.1 and later by my estimation.

**Comment by PascalBrouwers** [comment]
Yeah, I'm gonna try that. Tnx!
