### ISSUE TITLE
Add capistrano-pending Gem into deployment workflow

### ISSUE THREAD

**Issue by erikhansen** [davidalger/capistrano-magento2#8]
[capistrano-pending](https://github.com/a2ikm/capistrano-pending) is a really useful Gem that can be used to see what changes are about to be deployed to an environment.

I'd like to see usage of this Gem incorporated into the `capistrano-magento2`, similar to how you've included [terminal-notifier](https://github.com/davidalger/capistrano-magento2#terminal-notifier-on-os-x).

My proposal of how it would work:

Whenever you run `cap <STAGE> deploy`, you would see a list of all of the pending changes as the first output of the `deploy` command:
![16-01-22 pastedgraphic-1-vwow1](https://cloud.githubusercontent.com/assets/129031/15837823/7ce124fa-2c00-11e6-81f8-ade1edb5d6d9.png)

If there are no pending changes, the command would warn you about this and ask you if you wanted to continue deploying:

![16-06-07 pastedgraphic-2-ozf9f](https://cloud.githubusercontent.com/assets/129031/15837836/9bd9f512-2c00-11e6-98df-1bdeb3b9e060.png)

While a developer could just include the `capistrano-pending` Gem into their project and run `cap <STAGE> deploy:pending`, the benefit of my suggested approach is that they would automatically see pending changes AND wouldn't accidentally deploy "no changes", which I've done more than once.

If I were to submit a PR that implemented this change, would you accept it?

**Comment by davidalger** [comment]
@erikhansen I'm not sure how soon I could implement _and_ have the time to test this. If you were able to put together a PR, I would love to see this brought in!

Since it'd be adding a dependency, you'd want to make sure capistrano-pending is listed in `capistrano-magento2.gemspec` similar to how terminal-notifier is, and also run `bundler` to update the Gemfile.lock so that could be committed as well (that one is mostly for dev purposes).

Would you see this check coming before or after the deploy prompt I've got implemented (just asking for yes/no confirmation before it runs for an env named either 'prod' or 'production')?

**Comment by erikhansen** [comment]
@davidalger 

> Would you see this check coming before or after the deploy prompt I've got implemented (just asking for yes/no confirmation before it runs for an env named either 'prod' or 'production')?

I am planning on setting up the `deploy:pending` output to run before the production deploy prompt. My thought process around this is that showing the user the pending change log _before_ asking them whether they want to deploy will allow them to determine whether the branch they're deploying has the appropriate changes in it. The only downside to this is that the `deploy:pending` command can sometimes take 10-15 seconds to output any content, so the user might switch away from Terminal without realizing that the deploy won't continue unless they explicitly confirm that they want to deploy to production. 

Even when I haven't had a `deploy:pending` check in place, there have been several times where I've forgotten about a production deploy prompt and have switched back to Terminal minutes later, only to find out that my `cap prod deploy` command was not running as I failed to confirm that I wanted to deploy to production.

One thought about how to avoid the issue with users missing the production deploy prompt would be to trigger an OS X notification like _`"Are you sure you want to deploy to <STAGE>"`_. terminal-notifier supports removing notifications (see the [-remove flag](https://github.com/julienXX/terminal-notifier#readme)), so that notification could be removed once the user entered "y" or "N".

Would you accept two separate PRs that:
1. Adds the `deploy:pending` check before the production deploy prompt
2. Displays a _`"Are you sure you want to deploy to <STAGE>"`_ notification that would be dismissed when the user answered the prompt

**Comment by davidalger** [comment]
Available in 0.4.0. Closing. See PR for details.
