### ISSUE TITLE
Add app:config:import

### ISSUE THREAD

**Issue by giacmir** [davidalger/capistrano-magento2#83]
In Magento 2.2 there is a system to synchronize configurations from staging/dev to prod.
This is done by dumping configs in `config.php` while in dev and then aplying those config in prod via `app:config:import` or `setup:upgrade`.

details [here](http://devdocs.magento.com/guides/v2.2/config-guide/deployment/pipeline/)

If the configuration file has changed but the changes are not applied the website goes 500 until config are applied.

This gem does not neither `setup:upgrade` nor `app:config:import` and then website is broken.

**Comment by davidalger** [comment]
@giacmir Interesting. I was aware of and had read that overview page but not the technical detailed ones yet… 2.1 introduced config.local.php and 2.2 introduced the finalized version of this configuration system…and it seems the requirement to import the config from config.php and env.php to the database.

I'll get it taken care of; might take me a few days though.

**Comment by davidalger** [comment]
This has been implemented and released in v0.7.2. Thanks for the tip!
