### ISSUE TITLE
version check fails deploying Magento 2.2 B2B

### ISSUE THREAD

**Issue by avoelkl** [davidalger/capistrano-magento2#87]
Hi,

I got the following message deploying a Magento 2 B2B: 
```
11:23 magento:deploy:version_check
      ERROR Version 0.7.0 and later of this gem only support deployment of Magento 2.1.1 or newer; attempted to deploy v1.0.0. Please try again using an earlier version of this gem!

```

This fails because B2B starts with  1.0.0.

We encountered the same issue here before:
https://github.com/firegento/FireGento_FastSimpleImport2/pull/57/files

Best regards,
Anna

**Comment by avoelkl** [comment]
Also it seems this check fails and sets the pipefail option because our version is 1.0.0
https://github.com/davidalger/capistrano-magento2/blob/5e706d8913ac9f65d70747186a32e2c7b86e313f/lib/capistrano/magento2.rb#L41+
`sh: 1: set: Illegal option -o pipefail`

**Comment by davidalger** [comment]
@avoelkl Can you tell me what `bin/magento -- -V --no-ansi` reports?

**Comment by avoelkl** [comment]
sure, that's:

```
$ bin/magento -- -V --no-ansi
Magento CLI version 1.0.0
```

**Comment by avoelkl** [comment]
Thanks to @davidalger 's input I've udated our composer.json now like this:

```
-        "magento/product-b2b-edition": "1.0.0",
+        "magento/extension-b2b": "^1.0",
```

This is according to the B2B setup recommended here: [http://devdocs.magento.com/guides/v2.2/comp-mgr/install-extensions/b2b-installation.html](http://devdocs.magento.com/guides/v2.2/comp-mgr/install-extensions/b2b-installation.html).

The version is now reported correctly via bin/magento.
