### ISSUE TITLE
When deployment fails, site is not coming out of maintenance mode

### ISSUE THREAD

**Issue by dverkade** [davidalger/capistrano-magento2#91]
When deployment fails in the data upgrade, site is not coming out of maintenance mode and is stuck there. Is it possible to disable the maintenance mode on the current version if the data upgrade fails?

**Comment by giacmir** [comment]
When a data-upgrade fails you may have something broken. My personal opinion is that it is not safe to automatically exit maintenance mode. Better check if anything is wrong and disable maintenance by hand.

**Comment by davidalger** [comment]
My thoughts concur with @giacmir and is why it is designed this way. Once the site goes into maintenance, any errors that may be encountered may leave the deployment target in an unpredictable state, so it's better to fail and leave it up to the deployer to resolve.
