### ISSUE TITLE
Override magento:composer:install to get rid of --no-dev flag

### ISSUE THREAD

**Issue by adexandros** [davidalger/capistrano-magento2#96]
Hello,

is it possible to override the composer install command so that the flag `--no-dev` can be removed?
At the moment the staging environment I am deploying to is in developer mode and needs to have installed the dependencies that are under "`required-dev`", is this somewhat possible?
I've tried to copy paste the `namespace :composer do` from `magento.rake` to `deploy.rake` under `tools/cap/lib/capistrano/tasks` or add `magento.rake` in the same folder but without success.

thank you

**Comment by davidalger** [comment]
@adexandros Sorry about the delay in replying here. Not sure I have a handy solution here. I know it's possible to override rake tasks from a project configuration, including those inside a gem that's included, but I'm unfortunately not quite familiar enough with rake (what powers capistrano) to know how to do this.

**Comment by davidalger** [comment]
@adexandros Followup here. Magento 2.3 beta it seems won't deploy with --no-dev currently, and I just added a setting in v0.8.5 to disable the use of --no-dev during deployment. Know it's late, but HTH some how.

To use this, simply add the following line to your deploy.rb file:

    set :magento_deploy_no_dev, false
